### ISSUE TITLE
cannot install rai-chem

### ISSUE THREAD

**Issue by CLG68** [vtarasv/pocket-cfdm#1]
Hi,

Sadly, I can't install rai-chem... 

I just wrote this issue in github/rai-chem:

"The requirement rdkit-pypi==2022.9.1, can't be resolved by pip.  Pip does not want to install rdkit 2022.9.1.  I can install this version through conda but it still does not want to go through.

I am stuck as rai-chem is needed for pocket-cfdm.

ERROR: Could not find a version that satisfies the requirement rdkit-pypi==2022.9.1 (from rai-chem) (from versions: 2022.9.2, 2022.9.3, 2022.9.4, 2022.9.5, 2023.3.1b1)
ERROR: No matching distribution found for rdkit-pypi==2022.9.1"

Is there a way around this?

Thanks,
Christian

**Comment by vtarasv** [comment]
https://github.com/vtarasv/rai-chem/issues/1#issue-2287849371

**Comment by CLG68** [comment]
Thank you,
