### ISSUE TITLE
dependencies and requirements missing

### ISSUE THREAD

**Issue by CLG68** [vtarasv/pocket-cfdm#2]
Hi,

To update your requirements: torch_scatter and torch_cluster need to be installed.  

when I run predict.py, I get

sh: 1: reduce: not found
sh: 1: reduce: not found

and other errors but probably related to the "reduce" problem

Do I need to install: https://github.com/rlabduke/reduce ?

**Comment by CLG68** [comment]
I installed reduce and is solved that problems but I have other problems I can't resolve with the environment

**Comment by vtarasv** [comment]
Hi,

Thanks for highlighting the issue. You are right, [reduce](https://github.com/rlabduke/reduce) should be included in the requirements.

What are the other issues?

**Comment by CLG68** [comment]
I think they are related to the environment.  Which version of cuda-toolkit, pytorch, torch-scatter and torch-cluster are you using in your environment?

**Comment by vtarasv** [comment]
I use nvcr.io/nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04 for the Docker image as per `Dockerfile`.
It also should work on the newer cuda version (I use cuda 12.2 locally).
The troch / torch_geometric versions can be found in the `requirements_dev.txt`.
